project:
  type: website
  output-dir: .

website:
  title: "Steven García Goñi"
  description: "Un sitio para compartir ingeniería y estadística"
  favicon: images\logo.png
  navbar:
    logo: images\logo.png
    logo-alt: "Logo de un cuervo"
    background: "#222222"
    foreground: "#F1F5F5"
    left:
      - href: index.qmd
        text: Inicio
      - href: docencia.qmd
        text: Recursos académicos
      - href: resume.qmd
        text: Currículum
        target: _blank
      - href: logo.qmd
        text: Imagen personal
  page-footer: 
    border: true
    left: |
      Creado con [{{< iconify simple-icons:quarto title="Quarto Logo" label="Quarto Logo" >}} Quarto](https://quarto.org).
    right: |
      License: [CC BY NC SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0).
        
resources: 
  - docencia/Comprendiendo el valor P.pdf
format:
  html:
    theme: flatly
    toc: false
    lang: es-ES
    css: styles.css
    
    
